# -*- coding: utf-8 -*-
"""Madre_Pizza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j8SmcwZo9y5THqPTWhzcRAsw1oUnRND
"""

from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hola Mundo'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)